DROP EXTENSION IF EXISTS plpython3u WITH SCHEMA pg_catalog;
DROP EXTENSION IF EXISTS pgaudit WITH SCHEMA public;
DROP EXTENSION IF EXISTS pgcrypto WITH SCHEMA public;
DROP EXTENSION IF EXISTS "uuid-ossp" WITH SCHEMA public;

